title: 'Jules Massart'
description: "Personal page"
baseurl: ""
url: "https://jmassart.github.io"

header_pages:
  - index.md
  - cv.md
  - blog.md
  - contact.md

style: light

footer: ''

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console